spring:
  application:
    name: eureka-service

#server:
#  port: 8302
  
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0