server:
  port: 8080

springdoc:
  packagesToScan: es.uv.tfm.gatewayservice
  
spring:
  application:
    name: gatewayservice
    
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
      routes:
      - id: userService
        uri: http://localhost:8081/
        predicates:        - Path=/account/**, /auth/**
      - id: graphservice
        uri: http://localhost:8082/
        predicates:
        - Path=/graph/**
        filters:
        - RewritePath=/graph/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
           
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:s3cr3t@localhost:8761/eureka/
