server:
  port: 8080

spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      routes:
      - id: pruebaModule
        uri: http://localhost:8085/
        predicates:
        - Path=/prueba/**
      - id: userService
        uri: http://localhost:8081/
        predicates:        - Path=/account/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:s3cr3t@localhost:8761/eureka/
